#!/bin/bash

set -xeu

echo "Installing dependencies ..."
apt-get update
apt-get install -y python-pip python-virtualenv

git clone https://github.com/rcbops/rpc_component/
pushd rpc_component
  virtualenv --python=python3 .venv
  set +u
  source .venv/bin/activate
  set -u
  pip install .
popd

component dependency download-requirements --download-dir /opt

deactivate

echo "Deploying components ..."
/opt/rpc-component-1/gating/check/run
/opt/rpc-component-2/gating/check/run
